### PR TITLE
Drop generator attributes

### PR DESCRIPTION
**Pull request by hadley**
They don't appear to be used for anything, and interfere with code navigation.

### CODE REVIEW

**Comment by hadley** [comment]
Oh I missed where it was used. If you want to keep this behaviour, I think it would be a little easier to capture it when you use `log_appender()` etc. Alternatively it might be easier to keep the current behaviour but just set the generator attribute in a way that doesn't interfere with code search. I'll think about this a bit more.

**Comment by daroczig** [comment]
Usually, the generator is defined via `deparse(match.call())`, but you are right that it might be possible to capture how the fn was actually called one level up to `log_config_setter` (as that is being called from e.g. `log_appender`). I'll try to play with this tomorrow :+1:

**Comment by hadley** [comment]
A simpler approach might just be to adopt a syntax like this:

```R
generator <- function(x) attr(x, "generator")
`generator<-` <- function(x, value) {
  attr(x, "generator") <- value
  x
}

appender_void <- function(lines) {}
generator(appender_void) <- quote(appender_void())
```

**Comment by daroczig** [comment]
I've spent some time trying to capture the `generator` in `log_config_setter` (basically via `match.call(definition = sys.function(-1), call = sys.call(-1))[[2]]`), but failed miserably with edge cases e.g. when calling `log_appender` in `do.call`, so I think we need to keep tracking the `generator` close to the function.

The above `generator` setter/getter approach works for me, although I am not sure yet how to use that elegantly with the factory functions, such as `appender_file` that returns a function now -- should it need to store the fn in a variable, call the `generator` setter, and then return on a 3rd line?

**Comment by hadley** [comment]
I'll take a pass through with the generator approach so you can see what you think. It might possibly also need a `set_generator()` function so you can also use inline.

**Pull request closed without merging**
