### PR TITLE
Added the namespace argument to log_shiny_input_changes

### PR DESCRIPTION
**Pull request by kpagacz**
Now allows emitting logs to a custom namespace.

I am happy to change it to accept `...` in the style of log_info, etc.

### CODE REVIEW

**Comment by Polkas** [comment]
+1 namespace argument will be a valuable improvement.

**Comment by kpagacz** [comment]
@daroczig Would you mind taking a look? This is an important piece of code for us.

**Review by daroczig — APPROVED** [review]
looks good, thanks

**Comment by kpagacz** [comment]
On a similar note, I wanted to ask you about any planned releases to CRAN. Do you maintain a schedule and do it manually or would you prefer to set up an automation pipeline for it?

**Comment by daroczig** [comment]
I doubt there might be any automation for CRAN releases :zipper_mouth_face: 
As something always comes up, e.g. with the most recent version of R devel or new checks.
I tend to do CRAN releases when a major feature or fix is introduced, or when I get pinged too many times :) Please feel free to open a GH ticket that I can follow.

**Comment by daroczig** [comment]
PS if you meant running R CMD check and the unit tests etc in a CI/CD, then I've just realized that Travis has been setup, but seems to be dead since ~July :thinking: 

I've opened #97 to migrate to Github Actions.

**Comment by m7pr** [comment]
Hey @daroczig your last CRAN release of teal logger was at 2021-10-19.
This does not cover this PR merged on 20221-12-01, which was 820 days ago. 
Would you mind releasing the updated version on CRAN?

**Comment by daroczig** [comment]
yeah, thanks for the bump -- will do by the end of this week :+1:

**Comment by m7pr** [comment]
Thank you! So much

**Pull request merged**
